import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from base import *
import re
from playwright.sync_api import sync_playwright

r = Registro(); srv = servir()
with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 1440, "height": 900}, accept_downloads=True)
    pg = ctx.new_page(); r.conectar(pg, "admin")

    print("Landing original")
    pg.goto(BASE + "/"); pg.wait_for_timeout(600)
    r.check("El vivero no es una colección de datos" in pg.get_by_role("heading", level=1).inner_text().replace("\n", " "), "landing original con su titular")
    boton = pg.locator(".aiden-hero-actions .aiden-button-dark").first
    r.check(boton.evaluate("e => getComputedStyle(e).color") == "rgb(255, 253, 248)", "botón oscuro del hero con el texto crema de la paleta (antes heredaba el oscuro)")
    r.check(pg.locator(".aiden-roles .aiden-section-header > p").evaluate("e => getComputedStyle(e).color") != "rgba(255, 253, 248, 0.64)", "párrafo de Roles visible sobre fondo claro")
    activos = pg.locator(".aiden-product-frame strong").first.inner_text()
    r.check(activos not in ("00", "0"), f"vista previa del hero con datos reales ({activos} lotes activos)")
    pg.get_by_role("link", name="Supervisor:").click(); pg.wait_for_url("**/login?cuenta=supervisor")
    r.check(pg.locator("input[type=email]").input_value() == "supervisor@aiden.com", "fila de Roles precarga la cuenta demo")

    print("Login admin")
    entrar(pg, "admin")
    r.check("/dashboard-admin" in pg.url, "admin llega a su tablero")
    r.check(pg.get_by_role("heading", name="Centro de administración").is_visible(), "Centro de administración original")
    r.check(pg.get_by_text("Alertas que requieren decisión").is_visible(), "tarjeta oscura de decisiones")
    r.check(pg.locator(".recharts-bar-rectangle").count() > 0, "gráfica de ingresos y gastos con barras")

    print("Producción: crear lote")
    pg.goto(BASE + "/produccion"); pg.wait_for_timeout(300)
    tarjetas = pg.get_by_role("button", name=re.compile("^Ver lote "))
    tarjetas.first.wait_for(timeout=8000)
    antes = tarjetas.count()
    pg.get_by_role("button", name="Nuevo lote").click()
    dlg = pg.get_by_role("dialog")
    codigo = dlg.get_by_label("Código").input_value()
    r.check(codigo == "LT-2026-018", f"código sugerido consecutivo ({codigo})")
    dlg.get_by_role("button", name="Crear lote").click()
    r.check(dlg.get_by_role("alert").filter(has_text="cultivo").is_visible(), "validación: exige cultivo")
    dlg.get_by_label("Cultivo y variedad").fill("Lulo La Selva")
    dlg.get_by_label("Plantas sembradas").fill("500")
    dlg.get_by_role("button", name="Crear lote").click()
    r.check(toast(pg, "Lote LT-2026-018 creado"), "aviso de lote creado")
    pg.wait_for_timeout(300)
    r.check(tarjetas.count() == antes + 1, "la lista de etapas suma el lote nuevo")

    print("Ficha y avance de etapa")
    pg.get_by_role("button", name="Ver lote LT-2026-018").click()
    ficha = pg.get_by_role("dialog")
    r.check(ficha.get_by_role("heading", name="Lote LT-2026-018").is_visible() and ficha.get_by_text("Lulo La Selva").first.is_visible(), "ficha del lote abre")
    r.check(ficha.get_by_text("Registro de lote").first.is_visible(), "historia registra la creación")
    ficha.get_by_role("button", name="Avanzar de etapa").click()
    pg.get_by_role("button", name="Pasar a Adaptación").click()
    r.check(toast(pg, "pasó a Adaptación"), "avanzar etapa con confirmación")
    pg.wait_for_timeout(300)
    r.check(pg.get_by_role("dialog").get_by_text("Cambio de etapa").first.is_visible(), "cambio de etapa queda en historia")
    pg.keyboard.press("Escape"); pg.wait_for_timeout(300)
    r.check(pg.get_by_role("dialog").count() == 0, "Escape cierra la ficha")

    print("Inventario: salida cargada al lote")
    pg.goto(BASE + "/inventario"); pg.wait_for_timeout(300)
    fila = pg.locator("table tbody tr").filter(has_text="Fertilizante").first
    insumo = fila.locator("td").first.locator("p").first.inner_text()
    fila.get_by_role("button", name="Mover").click()
    dlg = pg.get_by_role("dialog")
    dlg.get_by_text("Salida", exact=True).click()
    dlg.get_by_label("Cantidad").fill("99999")
    r.check(dlg.get_by_text("Solo hay").is_visible(), "valida salida mayor al stock")
    dlg.get_by_label("Cantidad").fill("2")
    dlg.get_by_label("Lote que lo usa").select_option("LT-2026-018")
    r.check(dlg.get_by_text("al costo de LT-2026-018").is_visible(), "ofrece cargar el costo al lote")
    dlg.get_by_role("button", name="Guardar movimiento").click()
    r.check(toast(pg, "Salida registrada"), "aviso de salida registrada")
    pg.goto(BASE + "/costos")
    r.check(visible(pg.locator("table").last.get_by_text(insumo).first), f"costo generado desde inventario ({insumo})")
    pg.goto(BASE + "/trazabilidad?lote=LT-2026-018"); pg.locator("ol li").first.wait_for(timeout=8000)
    r.check(pg.locator("ol li").filter(has_text="Consumo de insumo").filter(has_text="Fertilizante").count() == 1, "consumo aparece en la línea de vida del lote")

    print("Inventario desde alerta")
    pg.goto(BASE + "/dashboard-supervisor"); pg.wait_for_timeout(400)
    pg.get_by_role("link", name="Registrar entrada").first.click(); pg.wait_for_timeout(400)
    dlg = pg.get_by_role("dialog")
    r.check(dlg.get_by_role("heading", name="Registrar movimiento").is_visible(), "alerta de inventario abre la entrada precargada")
    dlg.get_by_label("Cantidad").fill("10"); dlg.get_by_role("button", name="Guardar movimiento").click()
    r.check(toast(pg, "Entrada registrada"), "entrada registrada desde la alerta")

    print("Calidad: cerrar exige acción")
    pg.goto(BASE + "/calidad"); pg.wait_for_timeout(300)
    tarjeta = pg.locator("article").filter(has_text="INC-031").first
    tarjeta.get_by_label("Estado de INC-031").select_option("Cerrada")
    r.check(tarjeta.get_by_role("alert").filter(has_text="acción correctiva").is_visible(), "no deja cerrar sin acción correctiva (en la tarjeta)")
    pg.goto(BASE + "/calidad?incidencia=INC-031"); pg.wait_for_timeout(400)
    panel = pg.get_by_role("dialog")
    panel.get_by_label("Acción correctiva").fill("Se ajustó la fertilización nitrogenada y se retiraron hojas afectadas.")
    panel.get_by_role("button", name="Cerrar incidencia").click()
    r.check(toast(pg, "INC-031 cerrada"), "incidencia cerrada con acción documentada")
    pg.wait_for_timeout(300)
    r.check(pg.get_by_role("dialog").get_by_role("button", name="Reabrir").is_visible(), "incidencia cerrada se puede reabrir")

    print("Configuración")
    pg.goto(BASE + "/configuracion"); pg.wait_for_timeout(300)
    antes = pg.get_by_role("status").filter(has_text="Con este rango").inner_text()
    pg.get_by_label("Temperatura máxima (°C)").fill("32")
    despues = pg.get_by_role("status").filter(has_text="Con este rango").inner_text()
    r.check(antes != despues, "vista previa del efecto del umbral")
    pg.get_by_role("button", name="Guardar cambios").click()
    r.check(toast(pg, "Cambios guardados"), "Guardar cambios del encabezado original")
    pg.get_by_label("Temperatura mínima (°C)").fill("35"); pg.get_by_role("button", name="Guardar cambios").click()
    r.check(pg.get_by_role("alert").filter(has_text="menor que la máxima").is_visible(), "valida mínima menor que máxima")

    print("Reportes")
    pg.goto(BASE + "/reportes"); pg.wait_for_timeout(300)
    pg.get_by_role("button", name="Rentabilidad por lote").click()
    with pg.expect_download() as d:
        pg.get_by_role("button", name="Exportar CSV").click()
    contenido = open(d.value.path(), encoding="utf-8-sig").read()
    r.check(contenido.startswith("Lote;Cultivo") and "LT-2026-018" in contenido, "CSV con BOM, ';' y el lote nuevo")

    print("Buscador de la barra superior e Inteligencia")
    pg.keyboard.press("Control+k"); pg.wait_for_timeout(200)
    pg.keyboard.type("aguacate"); pg.wait_for_timeout(200)
    pg.keyboard.press("Enter"); pg.wait_for_timeout(400)
    r.check(pg.get_by_role("dialog").get_by_role("heading", name="Lote LT-2026-013").is_visible(), "⌘K → buscar cultivo → Enter abre la ficha")
    pg.keyboard.press("Escape")
    pg.goto(BASE + "/ia"); pg.wait_for_timeout(300)
    pg.get_by_role("button", name="¿Qué insumos hay que comprar?").click(); pg.wait_for_timeout(300)
    r.check(pg.get_by_text("Calculado con los datos actuales de Inventario").is_visible(), "Inteligencia responde y cita la fuente")
    pg.get_by_label("Pregunta sobre la operación").fill("cuéntame un chiste"); pg.keyboard.press("Enter"); pg.wait_for_timeout(200)
    r.check(pg.get_by_text("No tengo una regla").is_visible(), "Inteligencia reconoce cuando no sabe")

    print("Accesos y 404")
    pg.goto(BASE + "/personal?vista=accesos"); pg.wait_for_timeout(300)
    r.check(pg.get_by_role("tab", name="Accesos").get_attribute("aria-selected") == "true", "vista de accesos por URL")
    r.check(pg.get_by_label("Rol de Jordan Aragon").is_disabled(), "no puede cambiar su propio rol")
    pg.goto(BASE + "/no-existe"); pg.wait_for_timeout(300)
    r.check(pg.get_by_role("heading", name="Esta página no existe.").is_visible(), "página 404")
    b.close()
srv.shutdown(); r.resumen()
