import os, sys, re; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from base import *
from playwright.sync_api import sync_playwright

r = Registro(); srv = servir()
with sync_playwright() as p:
    b = p.chromium.launch()

    print("Supervisor")
    ctx = b.new_context(viewport={"width": 1440, "height": 900}); pg = ctx.new_page(); r.conectar(pg, "supervisor")
    entrar(pg, "supervisor")
    r.check(visible(pg.get_by_role("heading", name="Centro de supervisión")), "Centro de supervisión original")
    r.check(pg.get_by_role("navigation", name="Menú principal").first.get_by_role("link", name="Configuración").count() == 0, "supervisor no ve Configuración en el menú")
    atencion = pg.locator("article").filter(has=pg.get_by_role("heading", name="Atención inmediata")).locator("article")
    r.check(atencion.count() >= 4, f"'Atención inmediata' con {atencion.count()} alertas")
    pg.get_by_role("button", name="Asignar revisión").first.click()
    dlg = pg.get_by_role("dialog")
    r.check(dlg.get_by_label("Qué hay que hacer").input_value().startswith("Revisar condiciones en"), "alerta ambiental precarga la tarea")
    dlg.get_by_role("button", name="Asignar tarea").click()
    r.check(toast(pg, "Tarea asignada"), "tarea asignada desde la alerta")
    pg.goto(BASE + "/configuracion"); pg.wait_for_url("**/dashboard-supervisor")
    r.check("/dashboard-supervisor" in pg.url, "supervisor redirigido si entra a /configuracion")
    pg.goto(BASE + "/personal?vista=tareas&filtro=vencidas")
    r.check(visible(pg.get_by_role("button", name=re.compile("^Vencidas"), pressed=True)), "filtro de vencidas por URL")
    r.check(pg.get_by_role("tab", name="Accesos").count() == 0, "supervisor no ve la pestaña Accesos")
    pg.goto(BASE + "/personal")
    pg.get_by_role("button", name=re.compile("^Andrés Rojas")).first.click()
    panel = pg.get_by_role("dialog")
    panel.get_by_role("button", name="Desactivar").click()
    pg.get_by_role("dialog").get_by_role("button", name="Desactivar").last.click()
    r.check(toast(pg, "reasigna"), "no deja desactivar a quien tiene trabajo asignado")
    ctx.close()

    print("Operario en móvil")
    ctx = b.new_context(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True); pg = ctx.new_page(); r.conectar(pg, "operario")
    entrar(pg, "operario")
    r.check("/dashboard-operario" in pg.url, "operario llega a Mi jornada")
    r.check(visible(pg.get_by_role("heading", name="Lo que tengo que hacer")), "ve 'Lo que tengo que hacer'")
    hecha = pg.get_by_role("button", name="Hecha", exact=True)
    antes = hecha.count()
    hecha.first.click()
    dlg = pg.get_by_role("dialog")
    dlg.get_by_label("Nota para supervisión").fill("Hecho con 20 litros de mezcla")
    dlg.get_by_role("button", name="Marcar hecha").click()
    r.check(toast(pg, "Tarea completada"), "completa una tarea con nota")
    pg.wait_for_timeout(300)
    r.check(hecha.count() == antes - 1, "la tarea sale de pendientes")
    r.check(pg.get_by_role("region", name="Hechas hoy").count() == 1, "aparece en 'Hechas hoy'")
    pg.get_by_role("button", name="Tomar lectura").click()
    dlg = pg.get_by_role("dialog")
    dlg.get_by_label("Temperatura (°C)").fill("31.5"); dlg.get_by_label("Humedad (%)").fill("60")
    r.check(dlg.get_by_role("status").filter(has_text="quedará en alerta").is_visible(), "previsualiza que la lectura quedará en alerta")
    dlg.get_by_role("button", name="Guardar lectura").click()
    r.check(toast(pg, "en alerta"), "lectura guardada y marcada en alerta")
    pg.get_by_role("button", name="Reportar problema").click()
    dlg = pg.get_by_role("dialog")
    dlg.get_by_label("Qué observaste").fill("Trips en el envés de las hojas de la mesa 2")
    dlg.get_by_text("Alta", exact=True).click()
    dlg.get_by_role("button", name="Reportar incidencia").click()
    r.check(toast(pg, "Incidencia INC-033 registrada"), "reporta incidencia con código consecutivo")
    pg.goto(BASE + "/inventario"); pg.wait_for_url("**/dashboard-operario")
    r.check("/dashboard-operario" in pg.url, "operario no entra a Inventario")
    pg.goto(BASE + "/produccion")
    r.check(visible(pg.get_by_text("Mis lotes", exact=True)), "Producción muestra 'Mis lotes'")
    r.check(pg.get_by_role("button", name="Nuevo lote").count() == 0, "operario no crea lotes")
    ancho = pg.evaluate("document.documentElement.scrollWidth")
    r.check(ancho <= 390, f"sin desborde horizontal en móvil ({ancho}px)")
    buscador = pg.get_by_label("Buscar módulos y registros").bounding_box()
    menu = pg.get_by_role("button", name="Abrir menú de navegación").bounding_box()
    r.check(buscador["x"] >= menu["x"] + menu["width"], "la hamburguesa ya no tapa el buscador")
    pg.get_by_role("button", name="Abrir menú de navegación").click(); pg.wait_for_timeout(300)
    r.check(pg.get_by_role("link", name="Costos").count() == 0, "menú del operario sin módulos de gestión")
    ctx.close()

    print("Supervisor ve lo que hizo el operario")
    ctx = b.new_context(viewport={"width": 1440, "height": 900}); pg = ctx.new_page(); r.conectar(pg, "cruce")
    entrar(pg, "operario")
    pg.get_by_role("button", name="Hecha", exact=True).first.click()
    pg.get_by_role("dialog").get_by_role("button", name="Marcar hecha").click(); pg.wait_for_timeout(300)
    pg.get_by_role("button", name="Cuenta").click(); pg.get_by_role("button", name="Cerrar sesión").click()
    pg.wait_for_url("**/login"); entrar(pg, "supervisor")
    r.check("/dashboard-supervisor" in pg.url, "tras cerrar sesión, la siguiente cuenta entra a su propio tablero")
    r.check(visible(pg.get_by_text("1 completadas hoy")), "el supervisor ve la tarea completada por el operario")
    pg.goto(BASE + "/trazabilidad"); pg.locator("ol li").first.wait_for(timeout=8000)
    r.check(pg.locator("ol li").filter(has_text="Tarea completada").filter(has_text="Andrés").count() >= 1, "la tarea completada entra a la trazabilidad")
    ctx.close()

    print("Registro y revisión de cuenta")
    ctx = b.new_context(viewport={"width": 1280, "height": 900}); pg = ctx.new_page(); r.conectar(pg, "registro")
    pg.goto(BASE + "/signup")
    pg.get_by_label("Nombre completo").fill("Camila Ortiz"); pg.get_by_label("Correo electrónico").fill("camila@vivero.com")
    pg.get_by_label("Contraseña", exact=True).fill("clave12345"); pg.get_by_label("Confirmar contraseña").fill("otra-clave")
    pg.locator("#legal").check(); pg.get_by_role("button", name="Crear cuenta").click()
    r.check(visible(pg.get_by_text("Las contraseñas no coinciden.")), "registro valida la confirmación")
    pg.get_by_label("Confirmar contraseña").fill("clave12345"); pg.get_by_role("button", name="Crear cuenta").click()
    pg.wait_for_url("**/login")
    r.check(visible(pg.get_by_text("Cuenta creada")), "registro vuelve al login con confirmación (flujo original)")
    pg.locator("input[type=email]").fill("camila@vivero.com"); pg.locator("input[type=password]").fill("clave12345")
    pg.get_by_role("button", name="Iniciar sesión", exact=True).click(); pg.wait_for_url("**/dashboard-operario")
    r.check(visible(pg.get_by_text("No tienes tareas asignadas")), "cuenta nueva ve estado vacío útil")
    pg.get_by_role("button", name="Cuenta").click(); pg.get_by_role("button", name="Cerrar sesión").click(); pg.wait_for_url("**/login")
    entrar(pg, "admin")
    r.check(visible(pg.get_by_text("Cuenta nueva: Camila Ortiz")), "admin ve la cuenta nueva en sus decisiones")
    pg.goto(BASE + "/personal?vista=accesos")
    pg.get_by_label("Rol de Camila Ortiz").select_option("supervisor")
    pg.get_by_role("button", name="Cambiar rol").click()
    r.check(toast(pg, "Camila Ortiz ahora es supervisor"), "admin cambia el rol")
    pg.goto(BASE + "/personal")
    r.check(visible(pg.get_by_role("button", name=re.compile("^Camila Ortiz"))), "la cuenta nueva tiene ficha en Personal")
    pg.goto(BASE + "/configuracion")
    pg.get_by_role("button", name="Restablecer demo").click()
    pg.get_by_role("dialog").get_by_role("button", name="Restablecer").click()
    r.check(toast(pg, "restablecidos"), "restablecer demo")
    pg.goto(BASE + "/personal")
    r.check(visible(pg.get_by_role("button", name=re.compile("^Camila Ortiz"))), "tras restablecer, las cuentas conservan su ficha")
    ctx.close()
    b.close()
srv.shutdown(); r.resumen()
